"""Golden pin for a small mel filterbank; drift must be deliberate.

Values generated by executing mel_filterbank(8000, 16, 2, 0.0, 4000.0).
"""

import numpy as np

from slotvox.features.mel import mel_filterbank

GOLDEN_BANK = np.array(
    [
        [0.0, 0.80569817, 0.67591702, 0.24884042, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.32408298, 0.75115958, 0.90552231, 0.67914174, 0.45276116, 0.22638058, 0.0],
    ]
)


def test_small_filterbank_matches_golden():
    banks = mel_filterbank(8000, 16, 2, 0.0, 4000.0)
    assert banks.shape == GOLDEN_BANK.shape
    assert np.allclose(banks, GOLDEN_BANK, atol=1e-8)


def test_golden_bank_rows_are_nonzero_and_bounded():
    assert np.all(GOLDEN_BANK.min(axis=1) >= 0.0)
    assert np.all(GOLDEN_BANK.max(axis=1) <= 1.0)
    assert np.all(GOLDEN_BANK.sum(axis=1) > 0.0)
