"""Golden pin for the log-mel frontend; drift must be deliberate.

Values generated by executing log_mel() on the golden signal below with
FeatureConfig(n_mels=8, fmin=50.0, fmax=3500.0).
"""

import numpy as np

from slotvox.config import FeatureConfig
from slotvox.features.frontend import log_mel

GOLDEN_CONFIG = FeatureConfig(n_mels=8, fmin=50.0, fmax=3500.0)

GOLDEN_LOG_MEL = np.array(
    [
        [
            2.895316,
            9.670475,
            8.113433,
            -4.783315,
            -8.92969,
            -11.6475525,
            -13.869975,
            -15.797331,
        ],
        [
            2.8944085,
            9.670477,
            8.113428,
            -4.7598095,
            -8.80483,
            -11.356142,
            -13.354175,
            -15.012692,
        ],
        [
            2.8929386,
            9.670481,
            8.113421,
            -4.722909,
            -8.630939,
            -11.013245,
            -12.852172,
            -14.381547,
        ],
        [
            2.8929386,
            9.670481,
            8.113421,
            -4.722909,
            -8.630939,
            -11.013245,
            -12.852172,
            -14.381547,
        ],
        [
            2.8944085,
            9.670477,
            8.113428,
            -4.7598095,
            -8.80483,
            -11.356142,
            -13.354175,
            -15.012692,
        ],
        [
            2.895316,
            9.670475,
            8.113433,
            -4.783315,
            -8.92969,
            -11.6475525,
            -13.869975,
            -15.797331,
        ],
    ],
    dtype=np.float32,
)


def golden_signal():
    return np.sin(2 * np.pi * 440 * np.arange(1200) / 16000).astype(np.float32)


def test_log_mel_matches_golden():
    feats = log_mel(golden_signal(), GOLDEN_CONFIG)
    assert feats.shape == (6, 8)
    assert np.allclose(feats, GOLDEN_LOG_MEL, atol=1e-5)
